spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:dev
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: testpassword
  sql:
    init:
      mode: always
      platform: postgresql
      continue-on-error: true