create table if not exists address (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street VARCHAR(250),
    city VARCHAR(250) NOT NULL,
    state VARCHAR(250) NOT NULL,
    zip_code VARCHAR(250),
    country VARCHAR(250) NOT NULL
);

create table if not exists person (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(250) NOT NULL,
    last_name VARCHAR(250) NOT NULL,
    address_id BIGINT REFERENCES address(id)
);

create unique index unique_full_name on person (upper(first_name), upper(last_name));